title: Xiaowei Shi
logo: /assets/img/3D05927B-7C41-4D6A-A27B-0585AE872870.jpeg
description: Software / Medical engineer | M.S. Physics and engineering @ UCL '23
show_downloads: true
theme: jekyll-theme-minimal
